tempo:
  storage:
    trace:
      backend: s3
      s3:
        bucket: ${S3_BUCKET_TEMPO}
        endpoint: s3.${AWS_REGION}.amazonaws.com
        region: ${AWS_REGION}
        insecure: false

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-server.monitoring.svc.cluster.local:9090/api/v1/write"

  extraEnvFrom:
    - secretRef:
        name: aws-credentials
