server:
  replicaCount: 2

  persistentVolume:
    enabled: false

  service:
    type: ClusterIP
    servicePort: 9090

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - prometheus-server
          topologyKey: kubernetes.io/hostname
          
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["opentelemetry-collector.monitoring.svc.cluster.local:8888"]
