server:
  replicaCount: 2

  extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver

  persistentVolume:
    enabled: false

  service:
    type: ClusterIP
    servicePort: 9090

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - prometheus-server
          topologyKey: kubernetes.io/hostname

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

serviceAccounts:
  server:
    create: true
    name: prometheus-server

ingress:
  enabled: false
