community:
  enabled: true

postgresql:
  enabled: false

jdbcOverwrite:
  enabled: true
  jdbcUrl: ${RDS_ENDPOINT}
  jdbcUsername: ${RDS_USERNAME}
  jdbcPassword: ${RDS_PASSWORD}

service:
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - name: ${ALB_DNS_NAME}
      path: /sonarqube
      pathType: Prefix
      serviceName: sonarqube-sonarqube
      servicePort: 9000
  annotations:
    nginx.ingress.kubernetes.io/x-forwarded-port: "true"
    nginx.ingress.kubernetes.io/x-forwarded-host: "true"

sonarProperties:
  sonar.web.context: "/sonarqube"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring

monitoringPasscode: "fiap-hackathon-sonarqube-secret"