# controller:
#   kind: DaemonSet

# config:
#   service: |
#     [SERVICE]
#         Flush                                  1
#         Log_Level                              info

#   inputs: |
#     [INPUT]
#         Name                                   tail
#         Path                                   /var/log/containers/*.log
#         Tag                                    kube.*

#   filters: |
#     [FILTER]
#         Name                                   kubernetes
#         Match                                  kube.*
#         Merge_Log                              On
    
#     [FILTER]
#         Name                                   grep
#         Match                                  kube.*
#         Regex                                  kubernetes.namespace_name otel-test

#   outputs: |
#     [OUTPUT]
#         Name                                   opentelemetry
#         Match                                  *
#         Host                                   otel-collector-opentelemetry-collector.monitoring.svc.cluster.local
#         Port                                   4317
#         Grpc                                   on
#         logs_body_key                          $message
#         logs_span_id_message_key               span_id
#         logs_trace_id_message_key              trace_id
#         logs_severity_text_message_key         loglevel
#         logs_severity_number_message_key       lognum


config:
  inputs: |
    [INPUT]
        Name            tail
        Path            /var/log/containers/*.log
        Tag             kube.*
        Mem_Buf_Limit   5MB
        Skip_Long_Lines On

  outputs: |
    [OUTPUT]
        Name                             opentelemetry
        Match                            *
        Host                             otel-collector-opentelemetry-collector.monitoring.svc.cluster.local
        Port                             4317
        Grpc                             on
        logs_body_key                    $message
        logs_span_id_message_key         span_id
        logs_trace_id_message_key        trace_id
        logs_severity_text_message_key   loglevel
        logs_severity_number_message_key lognum

  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name    modify
        Match   kube.*
        Add     source eks
