global:
  extraEnvFrom:
    - secretRef:
        name: aws-credentials

loki:
  auth_enabled: false
  
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage_config:
    aws:
      region: ${AWS_REGION}
      bucketnames: ${LOKI_CHUNK_S3_BUCKET}
      s3forcepathstyle: false
  
  limits_config:
    allow_structured_metadata: true
    reject_old_samples: true
    reject_old_samples_max_age: 168h

  ingester:
    chunk_encoding: snappy

  pattern_ingester:
    enabled: true

  compactor:
    retention_enabled: true
    delete_request_store: s3

  ruler:
    enable_api: true
    storage:
      type: s3
      s3:
        region: ${AWS_REGION}
        bucketnames: ${LOKI_RULER_S3_BUCKET}
        s3forcepathstyle: false
      # alertmanager_url: http://prom:9093

  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
      chunks: ${LOKI_CHUNK_S3_BUCKET}
      ruler: ${LOKI_RULER_S3_BUCKET}
      # admin: "<Insert s3 bucket name>" # Your actual S3 bucket name (loki-aws-dev-admin) - GEL customers only
    s3:
      region: ${AWS_REGION}
      #insecure: false
    # s3forcepathstyle: false
  
  memcached:
    chunk_cache:
      enabled: true
      host: ""
      service: ${LOKI_MEMCACHED_CHUNK_CACHE_URL}
      batch_size: 256
      parallelism: 10
    results_cache:
      enabled: true
      host: ""
      service: ${LOKI_MEMCACHED_RESULTS_CACHE_URL}
      timeout: "500ms"
      default_validity: "12h"
  
serviceAccount:
  create: false

deploymentMode: Distributed

ingester:
  replicas: 2
  zoneAwareReplication:
    enabled: false

querier:
  replicas: 2
  maxUnavailable: 2

queryFrontend:
  replicas: 2
  maxUnavailable: 1

queryScheduler:
  replicas: 2

distributor:
  replicas: 2
  maxUnavailable: 1
compactor:
  replicas: 1

indexGateway:
  replicas: 2
  maxUnavailable: 1

ruler:
  replicas: 1
  maxUnavailable: 1

minio:
  enabled: false

chunksCache:
  enabled: false
  replicas: 0

resultsCache:
  enabled: false
  replicas: 0

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

singleBinary:
  replicas: 0

gateway:
  service:
    type: ClusterIP
    port: 3100