{
 "title": "Kubernetes Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Kubernetes Metrics - process API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "App pods running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=\"process\", phase=\"Running\", pod=~\"fiap-hackathon-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage - Application",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='process', pod=~'fiap-hackathon-.*'}[2m])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"fiap-hackathon-.*\", resource=\"cpu\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage - Application",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace='process', pod=~'fiap-hackathon-.*'}) by (pod)"
      }
     ]
    },
    {
     "title": "Avg pod CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='process', pod=~'fiap-hackathon-.*'}[2m])) / sum(kube_pod_container_resource_requests{pod=~\"fiap-hackathon-.*\", resource=\"cpu\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Metrics - mail API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "App pods running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=\"mail\", phase=\"Running\", pod=~\"fiap-hackathon-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage - Application",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='mail', pod=~'fiap-hackathon-.*'}[2m])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"fiap-hackathon-.*\", resource=\"cpu\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage - Application",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace='mail', pod=~'fiap-hackathon-.*'}) by (pod)"
      }
     ]
    },
    {
     "title": "Avg pod CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='mail', pod=~'fiap-hackathon-.*'}[2m])) / sum(kube_pod_container_resource_requests{pod=~\"fiap-hackathon-.*\", resource=\"cpu\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Metrics - video API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg pod CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='video', pod=~'fiap-hackathon-.*'}[2m])) / sum(kube_pod_container_resource_requests{pod=~\"fiap-hackathon-.*\", resource=\"cpu\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage - Application",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='video', pod=~'fiap-hackathon-.*'}[2m])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"fiap-hackathon-.*\", resource=\"cpu\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage - Application",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace='video', pod=~'fiap-hackathon-.*'}) by (pod)"
      }
     ]
    },
    {
     "title": "App pods running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{namespace=\"video\", phase=\"Running\", pod=~\"fiap-hackathon-.*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "NGINX Ingress Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}) ",
       "legendFormat": "nginx"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}[2m])) ",
       "legendFormat": "nginx"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per second (RPS)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{job=\"fiap-hackathon-microservices\", uri!~\"(.*actuator.*|.*swagger-ui.*|.*api-docs.*)\"}[1m])) by (uri)"
      }
     ]
    },
    {
     "title": "Total of Requests",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{job=\"fiap-hackathon-microservices\", uri!~\"(.*actuator.*|.*swagger-ui.*|.*api-docs.*)\"}[5m])) by (uri)"
      }
     ]
    }
   ]
  },
  {
   "title": "SonarQube Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "SonarQube UP Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"sonarqube\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sonarqube Up Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sonarqube_web_uptime_minutes", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}